/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SU30.c                                                *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  30                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x56FA (22266)                                *
* Character enabled:   0x4EF6 (20214)                                *
* Character enabled:   0x5347 (21319)                                *
* Character enabled:   0x7EA7 (32423)                                *
* Character enabled:   0x6B63 (27491)                                *
* Character enabled:   0x5728 (22312)                                *
* Character enabled:   0x8BF7 (35831)                                *
* Character enabled:   0x52FF (21247)                                *
* Character enabled:   0x89E6 (35302)                                *
* Character enabled:   0x6478 (25720)                                *
* Character enabled:   0x6309 (25353)                                *
* Character enabled:   0x952E (38190)                                *
* Character enabled:   0x6216 (25110)                                *
* Character enabled:   0x65AD (26029)                                *
* Character enabled:   0x5F00 (24320)                                *
* Character enabled:   0x6E90 (28304)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x63D2 (25554)                                *
* Character enabled:   0x5165 (20837)                                *
* Character enabled:   0x76D8 (30424)                                *
* Character enabled:   0x786E (30830)                                *
* Character enabled:   0x8BA4 (35748)                                *
* Character enabled:   0x55 (85)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSU30;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSU30_0055[ 34] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XX______,__XX____,
  XXX_____,_XX_____,
  _XXX____,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSU30_4EF6[ 63] = { /* code 4EF6 */
  _____XX_,______XX,________,
  _____XX_,__XX__XX,________,
  ____XX__,__XX__XX,________,
  ____XX__,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,XXXXXXXX,XXXXX___,
  ___XX___,XXXXXXXX,XXXXX___,
  __XXX__X,XX____XX,________,
  __XXX__X,X_____XX,________,
  _XXXX_XX,X_____XX,________,
  XX_XX__X,______XX,________,
  XX_XX___,______XX,________,
  ___XX_XX,XXXXXXXX,XXXXXX__,
  ___XX_XX,XXXXXXXX,XXXXXX__,
  ___XX___,______XX,________,
  ___XX___,______XX,________,
  ___XX___,______XX,________,
  ___XX___,______XX,________,
  ___XX___,______XX,________,
  ___XX___,______XX,________,
  ___XX___,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_5165[ 60] = { /* code 5165 */
  _______X,________,________,
  _______X,X_______,________,
  ________,XX______,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XXX____,________,
  ________,_XXX____,________,
  ________,_XXXX___,________,
  ________,XX__X___,________,
  ________,XX__XX__,________,
  _______X,XX___XX_,________,
  _______X,X____XX_,________,
  ______XX,______XX,________,
  _____XXX,______XX,________,
  _____XX_,_______X,X_______,
  ____XX__,________,XX______,
  ___XX___,________,XXX_____,
  _XXX____,________,_XXXX___,
  XXX_____,________,__XXXX__,
  _X______,________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_52FF[ 63] = { /* code 52FF */
  _____XX_,________,________,
  ____XXX_,________,________,
  ____XX__,________,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXX___,XX____XX,___XX___,
  __XX____,XX____XX,___XX___,
  _XX____X,XX____XX,___XX___,
  XX_____X,X____XXX,___XX___,
  X_____XX,X____XX_,__XX____,
  ______XX,_____XX_,__XX____,
  _____XXX,____XXX_,__XX____,
  ____XXX_,____XX__,__XX____,
  ___XXX__,___XXX__,__XX____,
  _XXXX___,___XX___,__XX____,
  XXX_____,__XX____,__XX____,
  _X______,_XXX____,__XX____,
  ________,XXX_____,_XXX____,
  ______XX,XX__XXXX,XXX_____,
  _____XXX,____XXXX,XX______,
  ______X_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_5347[ 63] = { /* code 5347 */
  ________,______XX,________,
  _______X,XXXX__XX,________,
  XXXXXXXX,XXXX__XX,________,
  XXXXXXX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  ____XXX_,______XX,________,
  ____XX__,______XX,________,
  ___XXX__,______XX,________,
  __XXX___,______XX,________,
  _XXX____,______XX,________,
  XXX_____,______XX,________,
  _X______,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_56FA[ 60] = { /* code 56FA */
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XX______,________,_XX_____,
  XX______,XX______,_XX_____,
  XX______,XX______,_XX_____,
  XX_XXXXX,XXXXXXXX,_XX_____,
  XX_XXXXX,XXXXXXXX,_XX_____,
  XX______,XX______,_XX_____,
  XX______,XX______,_XX_____,
  XX___XXX,XXXXXX__,_XX_____,
  XX___XXX,XXXXXX__,_XX_____,
  XX___XX_,____XX__,_XX_____,
  XX___XX_,____XX__,_XX_____,
  XX___XXX,XXXXXX__,_XX_____,
  XX___XXX,XXXXXX__,_XX_____,
  XX___XX_,____XX__,_XX_____,
  XX______,________,_XX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XX______,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_5728[ 66] = { /* code 5728 */
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ______XX,________,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________,
  ___XX___,____XX__,________,
  __XXX__X,XXXXXXXX,XXXX____,
  _XXXX__X,XXXXXXXX,XXXX____,
  _XXXX___,____XX__,________,
  XX_XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX_XX,XXXXXXXX,XXXXX___,
  ___XX_XX,XXXXXXXX,XXXXX___,
  ___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_5F00[ 60] = { /* code 5F00 */
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ___XX___,_____XX_,________,
  _XXXX___,_____XX_,________,
  XXX_____,_____XX_,________,
  _X______,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_6216[ 60] = { /* code 6216 */
  ________,____XX__,XX______,
  ________,____XX__,_XX_____,
  ________,____XX__,__XX____,
  ________,____XX__,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,____XX__,________,
  __XXXXXX,XX__XX__,________,
  __XXXXXX,XX__XX__,__X_____,
  __XX____,XX__XX__,_XXX____,
  __XX____,XX__XX__,_XX_____,
  __XX____,XX___XX_,_XX_____,
  __XXXXXX,XX___XX_,XX______,
  __XXXXXX,XX___XXX,X_______,
  __XX____,XX___XXX,X___XX__,
  __XX____,______XX,____XX__,
  _____XXX,XXX__XXX,____XX__,
  XXXXXXXX,XXX_XX_X,X___X___,
  XXXX____,__XXX___,XX_XX___,
  ________,_XX_____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_6309[ 63] = { /* code 6309 */
  ___XX___,_____X__,________,
  ___XX___,_____XX_,________,
  ___XX___,_____XX_,________,
  ___XX___,XXXXXXXX,XXXXX___,
  XXXXXXX_,XXXXXXXX,XXXXX___,
  XXXXXXX_,XX______,___XX___,
  ___XX___,XX__XX__,___XX___,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XXXX_,XXXXXXXX,XXXXXX__,
  __XXXXX_,XXXXXXXX,XXXXXX__,
  XXXXX___,_XX_____,_XX_____,
  XX_XX___,_X______,_XX_____,
  ___XX___,XX______,XX______,
  ___XX___,XXXX___X,XX______,
  ___XX___,__XXXXXX,X_______,
  ___XX___,_____XXX,X_______,
  ___XX___,____XXXX,XXX_____,
  ___XX___,_XXXXX__,_XXXX___,
  XXXXX_XX,XXXX____,___XXX__,
  XXXX___X,X_______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_63D2[ 66] = { /* code 63D2 */
  ___XX___,________,________,
  ___XX___,________,XXXXX___,
  ___XX___,XXXXXXXX,XXXXX___,
  ___XX___,XXXXXXXX,________,
  XXXXXXXX,_____XX_,________,
  XXXXXXXX,_____XX_,________,
  ___XX___,XXXXXXXX,XXXXXX__,
  ___XX___,XXXXXXXX,XXXXXX__,
  ___XX___,_____XX_,________,
  ___XX_X_,___XXXX_,________,
  ___XXXX_,XXXXXXX_,XXXXX___,
  _XXXXX__,XXXX_XX_,XXXXX___,
  XXXXX___,XX___XX_,___XX___,
  XX_XX___,XX___XX_,___XX___,
  ___XX___,XX___XX_,___XX___,
  ___XX___,XXXX_XX_,XXXXX___,
  ___XX___,XXXX_XX_,XXXXX___,
  ___XX___,XX___XX_,___XX___,
  ___XX___,XX___XX_,___XX___,
  ___XX___,XXXXXXXX,XXXXX___,
  XXXXX___,XXXXXXXX,XXXXX___,
  XXXX____,XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_6478[ 66] = { /* code 6478 */
  ___XX___,__XX___X,X_______,
  ___XX___,__XX___X,X_______,
  ___XX__X,XXXXXXXX,XXXXX___,
  ___XX__X,XXXXXXXX,XXXXX___,
  XXXXXXX_,__XX___X,X_______,
  XXXXXXX_,________,________,
  ___XX___,XXXXXXXX,XXXX____,
  ___XX___,XXXXXXXX,XXXX____,
  ___XX___,XX______,__XX____,
  ___XX___,XXXXXXXX,XXXX____,
  ___XXXX_,XXXXXXXX,XXXX____,
  __XXXXX_,XX______,__XX____,
  XXXXX___,XXXXXXXX,XXXX____,
  XX_XX___,XXXXXXXX,XXXX____,
  ___XX___,XX___XX_,__XX____,
  ___XX___,_____XX_,________,
  ___XX__X,XXXXXXXX,XXXXXX__,
  ___XX__X,XXXXXXXX,XXXXXX__,
  ___XX___,____XXXX,________,
  ___XX___,__XXX__X,XX______,
  XXXXX_XX,XXXX____,_XXXXX__,
  XXXX___X,X_______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_65AD[ 60] = { /* code 65AD */
  XX____XX,________,_XXX____,
  XXX___XX,_X_XXXXX,XXXX____,
  XXXX__XX,XXXXXXXX,X_______,
  XX_XX_XX,XX_XX___,________,
  XX_XX_XX,X__XX___,________,
  XX__XXXX,___XX___,________,
  XX____XX,___XX___,________,
  XXXXXXXX,XX_XXXXX,XXXXX___,
  XXXXXXXX,XX_XXXXX,XXXXX___,
  XX___XXX,___XX___,XX______,
  XX__XXXX,X__XX___,XX______,
  XX__XXXX,XX_XX___,XX______,
  XX_XX_XX,_XXXX___,XX______,
  XXXX__XX,__XXX___,XX______,
  XX____XX,___XX___,XX______,
  XX____XX,__XX____,XX______,
  XX____XX,__XX____,XX______,
  XXXXXXXX,_XX_____,XX______,
  XXXXXXXX,_XX_____,XX______,
  ________,XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_6B63[ 57] = { /* code 6B63 */
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XXXXXX,XXX_____,
  ___XX___,__XXXXXX,XXX_____,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_6E90[ 63] = { /* code 6E90 */
  XX______,________,________,
  _XX___XX,XXXXXXXX,XXXXX___,
  __X___XX,XXXXXXXX,XXXXX___,
  __XX__XX,_____XX_,________,
  ___XX_XX,____XX__,________,
  ______XX,_XXXXXXX,XXXX____,
  XX____XX,_XXXXXXX,XXXX____,
  _XX___XX,_XX_____,__XX____,
  __X___XX,_XXXXXXX,XXXX____,
  ___X__XX,_XXXXXXX,XXXX____,
  ___XX_XX,_XX_____,__XX____,
  ______XX,_XXXXXXX,XXXX____,
  ______XX,_XXXXXXX,XXXX____,
  __X___XX,_XX__XX_,__XX____,
  __XX_XXX,_____XX_,________,
  _XXX_XX_,__X__XX_,X_______,
  _XX__XX_,_XX__XX_,_X______,
  _XX__XX_,XX___XX_,_XXX____,
  _XX_XX_X,X____XX_,__XXX___,
  XX_XXX_X,__XXXXX_,___X____,
  XX__X___,__XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_7535[ 60] = { /* code 7535 */
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,XX______,___X____,
  ________,XX______,___XX___,
  ________,XX______,__XXX___,
  ________,XXXXXXXX,XXXX____,
  ________,_XXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_76D8[ 63] = { /* code 76D8 */
  ________,__XX____,________,
  ________,_XX_____,________,
  ____XXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,__XX____,XX______,
  ____XX__,___XX___,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ____XX__,X_______,XX______,
  ___XXX__,XXX_____,XX______,
  __XXX___,__XX_XXX,XX______,
  _XXX____,_____XXX,X_______,
  __X_____,________,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_786E[ 63] = { /* code 786E */
  ________,___XX___,________,
  ________,__XX____,________,
  XXXXXXX_,__XXXXXX,XX______,
  XXXXXXX_,_XXXXXXX,XX______,
  ___XX___,XX_____X,X_______,
  ___XX__X,X_____XX,________,
  ___X__XX,XXXXXXXX,XXXX____,
  __XX__X_,_XXXXXXX,XXXX____,
  __XXXXX_,_XX__XX_,__XX____,
  __XXXXX_,_XX__XX_,__XX____,
  _XXX_XX_,_XXXXXXX,XXXX____,
  _XXX_XX_,_XXXXXXX,XXXX____,
  XXXX_XX_,_XX__XX_,__XX____,
  X_XX_XX_,_XX__XX_,__XX____,
  __XX_XX_,_XXXXXXX,XXXX____,
  __XX_XX_,_XXXXXXX,XXXX____,
  __XXXXX_,_XX__XX_,__XX____,
  __XXXXX_,XX___XX_,__XX____,
  __XX____,XX___XX_,__XX____,
  __XX___X,X____XX_,XXXX____,
  _______X,X_______,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_7EA7[ 60] = { /* code 7EA7 */
  ____X___,________,________,
  ___XX___,XXXXXXXX,XXX_____,
  ___XX___,XXXXXXXX,XXX_____,
  __XX____,__XX____,_XX_____,
  _XX___X_,__XX____,XX______,
  _X___XX_,__XX____,XX______,
  XXXXXXX_,__XX___X,X_______,
  XXXXXX__,__XXX__X,XXXX____,
  ___XX___,__XXX__X,XXXX____,
  ___XX___,__XXX___,__XX____,
  __XX____,__XXXX__,_XX_____,
  _XXXXXXX,_XXX_X__,_XX_____,
  _XXXXXXX,_XXX_XX_,XX______,
  _XXX____,_XX__XXX,XX______,
  _____XX_,XXX___XX,X_______,
  __XXXXX_,XX____XX,X_______,
  XXXXX__X,XX___XXX,XXX_____,
  XX____XX,X___XX__,_XXX____,
  _____XXX,__XXX___,__XXXX__,
  ______X_,_XX_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_89E6[ 60] = { /* code 89E6 */
  ___XX___,_______X,X_______,
  __XX____,_______X,X_______,
  __XXXXX_,_______X,X_______,
  __X__XX_,_______X,X_______,
  _XX__XX_,___XXXXX,XXXXX___,
  XX___XX_,___XX__X,X__XX___,
  XXXXXXXX,X__XX__X,X__XX___,
  _XX_XX_X,X__XX__X,X__XX___,
  _XX_XX_X,X__XX__X,X__XX___,
  _XX_XX_X,X__XX__X,X__XX___,
  _XXXXXXX,X__XX__X,X__XX___,
  _XX_XX_X,X__XXXXX,XXXXX___,
  _XX_XX_X,X__XX__X,X_______,
  _XXXXXXX,X______X,X_______,
  _XX_XX_X,X______X,X_X_____,
  _XX_XX_X,X______X,X_XX____,
  _XX_XX_X,X______X,X__XX___,
  _X__XX_X,X______X,XXXXX___,
  XX__XX_X,X_XXXXXX,X___XX__,
  X____XXX,__XX____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_8BA4[ 60] = { /* code 8BA4 */
  __X_____,_____XX_,________,
  __XX____,_____XX_,________,
  ___XXX__,_____XX_,________,
  ____XXX_,_____XX_,________,
  _____X__,_____XX_,________,
  ________,_____XX_,________,
  ________,_____XX_,________,
  XXXXX___,_____XX_,________,
  XXXXX___,_____XXX,________,
  ___XX___,_____XXX,________,
  ___XX___,____XXXX,________,
  ___XX___,____XX_X,________,
  ___XX___,____X__X,X_______,
  ___XX___,X__XX__X,X_______,
  ___XX__X,X__X____,XX______,
  ___XX_XX,__XX____,XXX_____,
  ___XXX__,_XX_____,_XXX____,
  ___XX___,XX______,__XXX___,
  ___X___X,X_______,___XXX__,
  ______XX,________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_8BF7[ 63] = { /* code 8BF7 */
  ________,____XX__,________,
  _X______,____XX__,________,
  _XXX__XX,XXXXXXXX,XXXXX___,
  __XXX___,____XX__,________,
  ___X___X,XXXXXXXX,XXXX____,
  ________,____XX__,________,
  ________,____XX__,________,
  XXXX_XXX,XXXXXXXX,XXXXX___,
  XXXX____,________,________,
  __XX____,________,________,
  __XX___X,XXXXXXXX,XXX_____,
  __XX___X,X_______,_XX_____,
  __XX___X,X_______,_XX_____,
  __XX___X,XXXXXXXX,XXX_____,
  __XX___X,X_______,_XX_____,
  __XX_X_X,X_______,_XX_____,
  __XX_X_X,XXXXXXXX,XXX_____,
  __XXX__X,X_______,_XX_____,
  __XX___X,X_______,_XX_____,
  __X____X,X____XXX,XXX_____,
  _X_____X,X____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSU30_952E[ 66] = { /* code 952E */
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  __XX____,XXXX_XXX,XXXXX___,
  __XXXXX_,__XX___X,X__XX___,
  __XXXXX_,__X____X,X__XX___,
  _XX_____,_XX_XXXX,XXXXXXX_,
  _X______,XX_____X,X__XX___,
  XXXXXXX_,X______X,X__XX___,
  X_XXXXXX,X____XXX,XXXXX___,
  ___XX__X,XXXX___X,X__XX___,
  ___XX___,__XX___X,X_______,
  XXXXXXX_,__XX_XXX,XXXXX___,
  XXXXXXX_,__XX___X,X_______,
  ___XX__X,__XX___X,X_______,
  ___XX__X,XXX____X,X_______,
  ___XX_X_,XXX_XXXX,XXXXX___,
  ___XX_X_,XX_____X,X_______,
  ___XXX__,XXX____X,X_______,
  ___XX___,XXXXX___,________,
  __XX___X,X__XXXXX,XXXXXXX_,
  _______X,_____XXX,XXXXXX__,
  ______XX,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontSU30_CharInfo[23] = {
   {  12,  17,   2,   7,  16, acGUI_FontSU30_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  22,  21,   0,   6,  22, acGUI_FontSU30_4EF6 } /* code 4EF6 */
  ,{  22,  20,   0,   6,  22, acGUI_FontSU30_5165 } /* code 5165 */
  ,{  21,  21,   0,   6,  22, acGUI_FontSU30_52FF } /* code 52FF */
  ,{  21,  21,   1,   6,  22, acGUI_FontSU30_5347 } /* code 5347 */
  ,{  19,  20,   2,   7,  22, acGUI_FontSU30_56FA } /* code 56FA */
  ,{  21,  22,   1,   5,  22, acGUI_FontSU30_5728 } /* code 5728 */
  ,{  20,  20,   1,   7,  22, acGUI_FontSU30_5F00 } /* code 5F00 */
  ,{  22,  20,   0,   6,  22, acGUI_FontSU30_6216 } /* code 6216 */
  ,{  22,  21,   0,   6,  22, acGUI_FontSU30_6309 } /* code 6309 */
  ,{  22,  22,   0,   5,  22, acGUI_FontSU30_63D2 } /* code 63D2 */
  ,{  22,  22,   0,   5,  22, acGUI_FontSU30_6478 } /* code 6478 */
  ,{  21,  20,   1,   6,  22, acGUI_FontSU30_65AD } /* code 65AD */
  ,{  21,  19,   1,   7,  22, acGUI_FontSU30_6B63 } /* code 6B63 */
  ,{  21,  21,   1,   6,  22, acGUI_FontSU30_6E90 } /* code 6E90 */
  ,{  21,  20,   1,   6,  22, acGUI_FontSU30_7535 } /* code 7535 */
  ,{  22,  21,   0,   5,  22, acGUI_FontSU30_76D8 } /* code 76D8 */
  ,{  20,  21,   1,   5,  22, acGUI_FontSU30_786E } /* code 786E */
  ,{  22,  20,   0,   6,  22, acGUI_FontSU30_7EA7 } /* code 7EA7 */
  ,{  22,  20,   0,   6,  22, acGUI_FontSU30_89E6 } /* code 89E6 */
  ,{  22,  20,   0,   6,  22, acGUI_FontSU30_8BA4 } /* code 8BA4 */
  ,{  21,  21,   1,   6,  22, acGUI_FontSU30_8BF7 } /* code 8BF7 */
  ,{  23,  22,   0,   6,  22, acGUI_FontSU30_952E } /* code 952E */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop23 = {
   0x952E /* first character */
  ,0x952E /* last character  */
  ,&GUI_FontSU30_CharInfo[ 22] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop22 = {
   0x8BF7 /* first character */
  ,0x8BF7 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 21] /* address of first character */
  ,&GUI_FontSU30_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop21 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 20] /* address of first character */
  ,&GUI_FontSU30_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop20 = {
   0x89E6 /* first character */
  ,0x89E6 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 19] /* address of first character */
  ,&GUI_FontSU30_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop19 = {
   0x7EA7 /* first character */
  ,0x7EA7 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 18] /* address of first character */
  ,&GUI_FontSU30_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop18 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontSU30_CharInfo[ 17] /* address of first character */
  ,&GUI_FontSU30_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop17 = {
   0x76D8 /* first character */
  ,0x76D8 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 16] /* address of first character */
  ,&GUI_FontSU30_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop16 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 15] /* address of first character */
  ,&GUI_FontSU30_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop15 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 14] /* address of first character */
  ,&GUI_FontSU30_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop14 = {
   0x6B63 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 13] /* address of first character */
  ,&GUI_FontSU30_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop13 = {
   0x65AD /* first character */
  ,0x65AD /* last character  */
  ,&GUI_FontSU30_CharInfo[ 12] /* address of first character */
  ,&GUI_FontSU30_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop12 = {
   0x6478 /* first character */
  ,0x6478 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 11] /* address of first character */
  ,&GUI_FontSU30_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop11 = {
   0x63D2 /* first character */
  ,0x63D2 /* last character  */
  ,&GUI_FontSU30_CharInfo[ 10] /* address of first character */
  ,&GUI_FontSU30_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop10 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontSU30_CharInfo[  9] /* address of first character */
  ,&GUI_FontSU30_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop9 = {
   0x6216 /* first character */
  ,0x6216 /* last character  */
  ,&GUI_FontSU30_CharInfo[  8] /* address of first character */
  ,&GUI_FontSU30_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop8 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSU30_CharInfo[  7] /* address of first character */
  ,&GUI_FontSU30_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop7 = {
   0x5728 /* first character */
  ,0x5728 /* last character  */
  ,&GUI_FontSU30_CharInfo[  6] /* address of first character */
  ,&GUI_FontSU30_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop6 = {
   0x56FA /* first character */
  ,0x56FA /* last character  */
  ,&GUI_FontSU30_CharInfo[  5] /* address of first character */
  ,&GUI_FontSU30_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop5 = {
   0x5347 /* first character */
  ,0x5347 /* last character  */
  ,&GUI_FontSU30_CharInfo[  4] /* address of first character */
  ,&GUI_FontSU30_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop4 = {
   0x52FF /* first character */
  ,0x52FF /* last character  */
  ,&GUI_FontSU30_CharInfo[  3] /* address of first character */
  ,&GUI_FontSU30_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop3 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontSU30_CharInfo[  2] /* address of first character */
  ,&GUI_FontSU30_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop2 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_FontSU30_CharInfo[  1] /* address of first character */
  ,&GUI_FontSU30_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSU30_Prop1 = {
   0x0055 /* first character */
  ,0x0055 /* last character  */
  ,&GUI_FontSU30_CharInfo[  0] /* address of first character */
  ,&GUI_FontSU30_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSU30 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSU30_Prop1}
  ,24 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

